baseURL = "https://marek.onl"
languageCode = "en-us"
title = "Notes"
theme = "statine"
cleanDestinationDir = true
rssLimit = 100

# Taxonomies (only tags and categories are supported out of the box but you can
# add more)
[taxonomies]
    # category = "categories"
    tag = "tags"

[permalinks]
  [permalinks.term]
    tags = '/:slug/'

[params]
    # Site description. Individual pages can have descriptions too but if
    # missing it will fallback to that one.
    description = """Marek's notes"""

    # Enable pingback and webmention via webmention.io
    webmention = "marek.onl"

    [params.author]
        name = "Marek"
        email = "m@rek.onl"

# Sitemap location (default is /sitemap.xml)
[sitemap]
  filename = "sitemap.xml"

[minify]
  minifyOutput = true

[markup]
    [markup.tableOfContents]
        endLevel = 6
        startLevel = 2
    [markup.highlight]
        noclasses = false
    [markup.goldmark.renderer]
        unsafe = true
